on:
    push:
        tags:
            - "v3*"
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: ReleaseBuild
jobs:
    buildmac:
        name: MacOSX
        # env:
        #    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        runs-on: macos-latest
        steps:
            - name: Show Environment
              run: set | grep GIT
            - name: Setup Python environment
              # uses: actions/setup-python@v1.1.1
              uses: actions/setup-python@v2
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -a -A
            - name: Production Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 prerelease: False
                 files: release/*
    buildwindows:
        name: Windows
        # env:
        #    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        needs: buildmac
        runs-on: windows-latest
        steps:
            - name: Setup Python environment
              # uses: actions/setup-python@v1.1.1
              uses: actions/setup-python@v2
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -setupenv
            - name: Build project
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -all -everything
            - name: VirusTotal Upload
              shell: powershell
              if: startsWith(github.ref, 'refs/tags/v3')
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -virus
            - name: Production Release
              # uses: svenstaro/upload-release-action@v1-release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
    buildlinux:
        name: Linux
        # env:
        #    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        needs: buildmac
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python Environment
              # uses: actions/setup-python@v1.1.1
              uses: actions/setup-python@v2
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Linux Lib Install
              run: |
                cd $GITHUB_WORKSPACE
                bash linuxdeps.sh
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -a -A
            - name: Production Release
              # uses: svenstaro/upload-release-action@v1-release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
